paths:
  /register:
    post:
      tags:
      - "Register & Login"
      summary: "Register"
      description: "Register"
      operationId: "Register"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/register"
      responses:
        "405":
          description: "Invalid input"
  /login:
    post:
      tags:
      - "Register & Login"
      summary: "Login"
      description: "Login"
      operationId: "Login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/user"
      responses:
        "405":
          description: "Invalid input"
definitions:
    register:
      type: "Object"
      properties:
        name:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
        skype:
          type: "string"
        phoneNumber:
          type: "string"
          format: "int64"
        designation:
          type: "string"
        technology:
          type: "string"
      user:
        type: "Object"
        properties:
          email:
            type: "string"
          password:
            type: "string"